name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '16']
        year: [ '2020', '2021' ]
        #year: [ '2015', '2016', '2017', '2018', '2019', '2020', '2021' ]
    name: Java ${{matrix.java}}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
    - name: Run tests ${{ matrix.year }}
      run: sbt ${{ matrix.year }}/test
